name: Update semver tags
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: haya14busa/action-update-semver@v1 # TSCCR: no entry for action: "haya14busa/action-update-semver"